language: node_js
node_js:
  - "10"
sudo: required
addons:
  chrome: stable
cache:
  yarn: true
script:
  - mkdir coverage
  - yarn test-nyc
#  - yarn test-karma
#after_success:
#  - yarn run coveralls
