module.exports = {
  src: [
    './ts/react-hook.ts',
    './ts/web.ts',
    './ts/src/browser/browser-user-link.ts',
    './ts/src/requester/requester.ts',
    './ts/src/requester/node_cache.ts',
    './ts/src/requester/request.ts',
    './ts/src/requester/query/query-structure.ts',
    './ts/src/requester/query/result.ts',
    './ts/src/utils/async.ts',
    './ts/src/nodejs/client-link.ts',
    './ts/src/nodejs/cli-link-wrapper.ts',
    './ts/src/responder/base-local-node.ts',
    './ts/src/responder/node_state.ts',
    './ts/src/responder/responder.ts',
    './ts/src/responder/response.ts',
    './ts/src/responder/node/action-node.ts',
    './ts/src/responder/node/root-node.ts',
    './ts/src/responder/node/value-node.ts',
    './ts/src/responder/response/invoke.ts'
    // './ts/src/responder/response/subscribe.ts',
    // './ts/src/responder/response/list.ts',
  ],
  mode: 'file',
  tsconfig: 'tsconfig.json',
  out: './docs',
  excludePrivate: true,
  excludeProtected: true,
  excludeExternals: true,
  readme: 'docIndex.md',
  name: 'DSLink SDK',
  ignoreCompilerErrors: true,
  plugin: 'none'
};
